// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP1.Models;

#nullable disable

namespace SWP1.Migrations
{
    [DbContext(typeof(JeweleryOrderProduction1Context))]
    [Migration("20240605071149_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWP1.Models.CustomerDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address_line");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("DistrictTown")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district_town");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("province");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sex");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uid");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB857D6C9221");

                    b.HasIndex(new[] { "Uid" }, "UQ__Customer__DD70126518233B30")
                        .IsUnique();

                    b.ToTable("Customer_Detail", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Design", b =>
                {
                    b.Property<int>("DesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("design_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DesignatedCompletion")
                        .HasColumnType("date")
                        .HasColumnName("designated_completion");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int>("OrderCustomId")
                        .HasColumnType("int")
                        .HasColumnName("order_custom_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.HasKey("DesignId")
                        .HasName("PK__Design__1BA5C3FB1D7E47D5");

                    b.HasIndex("OrderCustomId");

                    b.HasIndex("OrderId");

                    b.ToTable("Design", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.DesignImage", b =>
                {
                    b.Property<int>("DesignImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("design_image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignImageId"));

                    b.Property<int>("DesignId")
                        .HasColumnType("int")
                        .HasColumnName("design_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.HasKey("DesignImageId")
                        .HasName("PK__Design_I__02A18B69AE54657F");

                    b.HasIndex("DesignId");

                    b.ToTable("Design_Images", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Gemstone", b =>
                {
                    b.Property<int>("GemstoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gemstone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GemstoneId"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("GemstoneCarat")
                        .HasColumnType("int")
                        .HasColumnName("gemstone_carat");

                    b.Property<string>("GemstoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gemstone_type");

                    b.HasKey("GemstoneId")
                        .HasName("PK__Gemstone__08CCD219CEDA5283");

                    b.HasIndex(new[] { "GemstoneType", "GemstoneCarat", "Color" }, "UQ__Gemstone__3E728275FAABF542")
                        .IsUnique()
                        .HasFilter("[color] IS NOT NULL");

                    b.ToTable("Gemstone", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Metal", b =>
                {
                    b.Property<int>("MetalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetalId"));

                    b.Property<string>("MetalTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("metal_type_name");

                    b.HasKey("MetalId")
                        .HasName("PK__Metals__15EB863C76CB438F");

                    b.HasIndex(new[] { "MetalTypeName" }, "UQ__Metals__EC08308C09FFA6E5")
                        .IsUnique();

                    b.ToTable("Metals");
                });

            modelBuilder.Entity("SWP1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit")
                        .HasColumnName("is_custom");

                    b.Property<bool>("IsShipment")
                        .HasColumnType("bit")
                        .HasColumnName("is_shipment");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_status");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("order_total");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("payment_status_id");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__46596229E8BBB67D");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SWP1.Models.OrderCustomItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("GemstoneId")
                        .HasColumnType("int")
                        .HasColumnName("gemstone_id");

                    b.Property<int>("MetalId")
                        .HasColumnType("int")
                        .HasColumnName("metal_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId")
                        .HasName("PK__Order_Cu__3764B6BC30FF0772");

                    b.HasIndex("GemstoneId");

                    b.HasIndex("MetalId");

                    b.HasIndex(new[] { "OrderId", "GemstoneId", "MetalId", "Size" }, "UQ__Order_Cu__1502BCB8FEC97BA0")
                        .IsUnique()
                        .HasFilter("[size] IS NOT NULL");

                    b.ToTable("Order_Custom_Items", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.OrderFixedItem", b =>
                {
                    b.Property<int>("OrderFixedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_fixed_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderFixedItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductStockId")
                        .HasColumnType("int")
                        .HasColumnName("product_stock_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderFixedItemId")
                        .HasName("PK__Order_Fi__A0C3DD8628D97D9E");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductStockId");

                    b.HasIndex(new[] { "OrderId", "ProductStockId" }, "UQ__Order_Fi__14E50BC22CDFA13C")
                        .IsUnique();

                    b.ToTable("Order_Fixed_Items", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status_name");

                    b.HasKey("PaymentStatusId")
                        .HasName("PK__Payment___E6BF50154C071B9C");

                    b.ToTable("Payment_Status", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_name");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__47027DF5E69C6D01");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex(new[] { "ProductName" }, "UQ__Product__2B5A6A5F7B3D399A")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<string>("Alt")
                        .HasColumnType("text")
                        .HasColumnName("alt");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("ProductStockId")
                        .HasColumnType("int")
                        .HasColumnName("product_stock_id");

                    b.HasKey("ProductImageId")
                        .HasName("PK__Product___0302EB4AE59968AB");

                    b.HasIndex("ProductStockId");

                    b.ToTable("Product_Images", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.ProductStock", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_stock_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductStockId"));

                    b.Property<string>("GalleryUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gallery_url");

                    b.Property<int>("GemstoneId")
                        .HasColumnType("int")
                        .HasColumnName("gemstone_id");

                    b.Property<int>("MetalId")
                        .HasColumnType("int")
                        .HasColumnName("metal_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.HasKey("ProductStockId")
                        .HasName("PK__Product___2BC69EA4502325B6");

                    b.HasIndex("GemstoneId");

                    b.HasIndex("MetalId");

                    b.HasIndex(new[] { "ProductId", "GemstoneId", "MetalId", "Size" }, "UQ__Product___1459A36433C02DA4")
                        .IsUnique()
                        .HasFilter("[size] IS NOT NULL");

                    b.ToTable("Product_Stock", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__Product___6EED3ED653FC3220");

                    b.HasIndex(new[] { "TypeName" }, "UQ__Product___543C4FD9E23A69D1")
                        .IsUnique();

                    b.ToTable("Product_Types", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.ProductionStatus", b =>
                {
                    b.Property<int>("ProductionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("production_status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status_name");

                    b.HasKey("ProductionStatusId")
                        .HasName("PK__Producti__182287F3F5396385");

                    b.ToTable("Production_Status", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.ProductionTracking", b =>
                {
                    b.Property<int>("ProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("production_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductionStatusId")
                        .HasColumnType("int")
                        .HasColumnName("production_status_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("ProductionId")
                        .HasName("PK__Producti__60F4D65CC9B6FBC3");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductionStatusId");

                    b.ToTable("Production_Tracking", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quote_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<decimal?>("CaratCost")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("carat_cost");

                    b.Property<decimal?>("CaratPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("carat_price");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("MetalCost")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("metal_cost");

                    b.Property<decimal?>("MetalWeight")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("metal_weight");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("ProductionCost")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("production_cost");

                    b.Property<decimal?>("QuoteTotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quote_total_price");

                    b.HasKey("QuoteId")
                        .HasName("PK__Quote__0D37DF0CAC11FD63");

                    b.HasIndex("OrderId");

                    b.ToTable("Quote", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.RequestImage", b =>
                {
                    b.Property<int>("RequestImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestImageId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("OrderCustomId")
                        .HasColumnType("int")
                        .HasColumnName("order_custom_id");

                    b.HasKey("RequestImageId")
                        .HasName("PK__Request___4212A850089C6B9B");

                    b.HasIndex("OrderCustomId");

                    b.ToTable("Request_Images", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review__60883D9064A2E871");

                    b.HasIndex("ProductId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__760965CC58BC597E");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__783254B14781B073")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SWP1.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<bool>("IsShipping")
                        .HasColumnType("bit")
                        .HasColumnName("is_shipping");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("shipment_date");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shipping_address");

                    b.Property<string>("ShippingDistrict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipping_district");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipping_province");

                    b.HasKey("ShipmentId")
                        .HasName("PK__Shipment__41466E590340BA74");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipment", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDetail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status_detail");

                    b.HasKey("StatusId")
                        .HasName("PK__Status__3683B5316AA6C15D");

                    b.HasIndex(new[] { "StatusDetail" }, "UQ__Status__1433E420E686241F")
                        .IsUnique();

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<bool>("IsDeposit")
                        .HasColumnType("bit")
                        .HasColumnName("is_deposit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_type");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<decimal>("TransactionTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("transaction_total");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__85C600AFCE28A483");

                    b.HasIndex("OrderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SWP1.Models.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Uid")
                        .HasName("PK__User__DD701264BE3EF2FB");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E616488495356")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__User__B43B145F570D159C")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SWP1.Models.CustomerDetail", b =>
                {
                    b.HasOne("SWP1.Models.User", "UidNavigation")
                        .WithOne("CustomerDetail")
                        .HasForeignKey("SWP1.Models.CustomerDetail", "Uid")
                        .IsRequired()
                        .HasConstraintName("FK__Customer_De__uid__2F10007B");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("SWP1.Models.Design", b =>
                {
                    b.HasOne("SWP1.Models.OrderCustomItem", "OrderCustom")
                        .WithMany("Designs")
                        .HasForeignKey("OrderCustomId")
                        .IsRequired()
                        .HasConstraintName("FK__Design__order_cu__5BE2A6F2");

                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("Designs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Design__order_id__5CD6CB2B");

                    b.Navigation("Order");

                    b.Navigation("OrderCustom");
                });

            modelBuilder.Entity("SWP1.Models.DesignImage", b =>
                {
                    b.HasOne("SWP1.Models.Design", "Design")
                        .WithMany("DesignImages")
                        .HasForeignKey("DesignId")
                        .IsRequired()
                        .HasConstraintName("FK__Design_Im__desig__5FB337D6");

                    b.Navigation("Design");
                });

            modelBuilder.Entity("SWP1.Models.Order", b =>
                {
                    b.HasOne("SWP1.Models.CustomerDetail", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__customer__46E78A0C");

                    b.HasOne("SWP1.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__payment___47DBAE45");

                    b.Navigation("Customer");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("SWP1.Models.OrderCustomItem", b =>
                {
                    b.HasOne("SWP1.Models.Gemstone", "Gemstone")
                        .WithMany("OrderCustomItems")
                        .HasForeignKey("GemstoneId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Cus__gemst__52593CB8");

                    b.HasOne("SWP1.Models.Metal", "Metal")
                        .WithMany("OrderCustomItems")
                        .HasForeignKey("MetalId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Cus__metal__534D60F1");

                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("OrderCustomItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Cus__order__5165187F");

                    b.Navigation("Gemstone");

                    b.Navigation("Metal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWP1.Models.OrderFixedItem", b =>
                {
                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("OrderFixedItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Fix__order__4BAC3F29");

                    b.HasOne("SWP1.Models.Product", "Product")
                        .WithMany("OrderFixedItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Fix__produ__4D94879B");

                    b.HasOne("SWP1.Models.ProductStock", "ProductStock")
                        .WithMany("OrderFixedItems")
                        .HasForeignKey("ProductStockId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Fix__produ__4CA06362");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("SWP1.Models.Product", b =>
                {
                    b.HasOne("SWP1.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Product__product__38996AB5");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("SWP1.Models.ProductImage", b =>
                {
                    b.HasOne("SWP1.Models.ProductStock", "ProductStock")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductStockId")
                        .IsRequired()
                        .HasConstraintName("FK__Product_I__produ__656C112C");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("SWP1.Models.ProductStock", b =>
                {
                    b.HasOne("SWP1.Models.Gemstone", "Gemstone")
                        .WithMany("ProductStocks")
                        .HasForeignKey("GemstoneId")
                        .IsRequired()
                        .HasConstraintName("FK__Product_S__gemst__403A8C7D");

                    b.HasOne("SWP1.Models.Metal", "Metal")
                        .WithMany("ProductStocks")
                        .HasForeignKey("MetalId")
                        .IsRequired()
                        .HasConstraintName("FK__Product_S__metal__412EB0B6");

                    b.HasOne("SWP1.Models.Product", "Product")
                        .WithMany("ProductStocks")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Product_S__produ__3F466844");

                    b.Navigation("Gemstone");

                    b.Navigation("Metal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP1.Models.ProductionTracking", b =>
                {
                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("ProductionTrackings")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__order__70DDC3D8");

                    b.HasOne("SWP1.Models.ProductionStatus", "ProductionStatus")
                        .WithMany("ProductionTrackings")
                        .HasForeignKey("ProductionStatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__produ__71D1E811");

                    b.Navigation("Order");

                    b.Navigation("ProductionStatus");
                });

            modelBuilder.Entity("SWP1.Models.Quote", b =>
                {
                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("Quotes")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Quote__order_id__59063A47");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWP1.Models.RequestImage", b =>
                {
                    b.HasOne("SWP1.Models.OrderCustomItem", "OrderCustom")
                        .WithMany("RequestImages")
                        .HasForeignKey("OrderCustomId")
                        .IsRequired()
                        .HasConstraintName("FK__Request_I__order__628FA481");

                    b.Navigation("OrderCustom");
                });

            modelBuilder.Entity("SWP1.Models.Review", b =>
                {
                    b.HasOne("SWP1.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__product___6C190EBB");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP1.Models.Shipment", b =>
                {
                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Shipment__order___68487DD7");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWP1.Models.Transaction", b =>
                {
                    b.HasOne("SWP1.Models.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__order__5629CD9C");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWP1.Models.User", b =>
                {
                    b.HasOne("SWP1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__role_id__29572725");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SWP1.Models.CustomerDetail", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SWP1.Models.Design", b =>
                {
                    b.Navigation("DesignImages");
                });

            modelBuilder.Entity("SWP1.Models.Gemstone", b =>
                {
                    b.Navigation("OrderCustomItems");

                    b.Navigation("ProductStocks");
                });

            modelBuilder.Entity("SWP1.Models.Metal", b =>
                {
                    b.Navigation("OrderCustomItems");

                    b.Navigation("ProductStocks");
                });

            modelBuilder.Entity("SWP1.Models.Order", b =>
                {
                    b.Navigation("Designs");

                    b.Navigation("OrderCustomItems");

                    b.Navigation("OrderFixedItems");

                    b.Navigation("ProductionTrackings");

                    b.Navigation("Quotes");

                    b.Navigation("Shipments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SWP1.Models.OrderCustomItem", b =>
                {
                    b.Navigation("Designs");

                    b.Navigation("RequestImages");
                });

            modelBuilder.Entity("SWP1.Models.PaymentStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SWP1.Models.Product", b =>
                {
                    b.Navigation("OrderFixedItems");

                    b.Navigation("ProductStocks");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SWP1.Models.ProductStock", b =>
                {
                    b.Navigation("OrderFixedItems");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("SWP1.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SWP1.Models.ProductionStatus", b =>
                {
                    b.Navigation("ProductionTrackings");
                });

            modelBuilder.Entity("SWP1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWP1.Models.User", b =>
                {
                    b.Navigation("CustomerDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
